default: &default
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV.fetch('DATABASE_PORT', '5432') %>
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: quiz-master-dev

test:
  <<: *default
  database: quiz-master-test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
