default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
<% if ENV.key?('DATABASE_URL') %>
  url: <%= ENV['DATABASE_URL'] %>
<% else %>
  database: quiz-master-dev
<% end %>

test:
  <<: *default
  database: quiz-master-test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
