default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: quiz-master-dev

test:
  <<: *default
  database: quiz-master-test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
