version: "3"
services:
  docs:
    build: ./docs
    command: yarn start
    volumes:
      - ./docs:/app
      - /app/node_modules
    restart: always
  ide:
    build: ./
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Japan
      - BUNDLE_PATH=/home/project/backend/vendor/bundle
      - GEM_HOME=/home/project/backend/vendor/bundle
      - DEFAULT_WORKSPACE=/home/project
    volumes:
      - ./.vscode:/config/data/User
      - ./favicon.ico:/app/code-server/src/browser/media/favicon.ico # set favicon of Quipper to editor
      - ./backend:/home/project/backend:cached
      - ./client:/home/project/client:cached
    restart: always
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./htpasswd:/etc/nginx/htpasswd
    ports:
      - 80:80
      - 443:443
    restart: always
