version: "3"
services:
  db:
    image: postgres:10.4
    volumes:
      - ./backend/tmp/db:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
    volumes:
      - ./backend:/app
      - ./backend/vendor/bundle:/vendor/bundle
    ports:
      - 3000:3000
  client:
    build: ./client
    command: yarn start
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 8080:8080
  docs:
    build: ./docs
    command: ./node_modules/.bin/docsify serve -p 3030 -b 0.0.0.0
    volumes:
      - ./docs:/app
      - /app/node_modules
    ports:
      - 3030:3030
