version: "3"
services:
  docs:
    build: ./docs
    command: yarn start
    volumes:
      - ./docs:/app
      - /app/node_modules
  ide:
    build: ./
    environment:
      - BUNDLE_PATH=/home/project/backend/vendor/bundle
      - GEM_HOME=/home/project/backend/vendor/bundle
    volumes:
      - ./backend:/home/project/backend:cached
      - ./client:/home/project/client:cached
  diff:
    build: ./diff
    command: yarn start
    volumes:
      - ./.git:/usr/src/app/.git
      - /usr/src/app/node_modules
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - docs
      - ide
      - diff
