version: '3'
services:
  #backend:
    #build: ./backend
    #command: bundle exec rails s -p 3000 -b '0.0.0.0'
    #volumes:
      #- ./backend:/myapp/backend
    #ports:
      #- "3000:3000"
  #client:
    #build: ./client
    #command: npm start
    #volumes:
      #- ./client:/myapp/client
    #ports:
      #- "8080:8080"
  docs:
    build: ./docs
    command: ./node_modules/.bin/docsify serve -p 3030 -b 0.0.0.0
    volumes:
      - ./docs:/app
      - /app/node_modules
    ports:
      - 3030:3030
